# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk16

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - name: Codecov
    uses: codecov/codecov-action@v3.1.0

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - 4ibo32@mail.ru
    on_success: never # default: change
on_failure: always # default: always